### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by ghost** [sunny/m3uh#1]
i cant get this work
![error](https://cloud.githubusercontent.com/assets/11785625/7010839/0b65bf14-dcad-11e4-8cee-2ce0d9833d18.jpg)

this is what i get

**Comment by sunny** [comment]
Hmm... That is weird since this script doesn't use CURL at all.

The errors seems to come from WordPress since it is in `/blog/wp-admin/`. It looks like WordPress is taking over. Please try and load the script from another directory than WordPress.
